# Generated by Django 5.1.3 on 2024-11-29 16:36

from django.db import migrations

def add_default_departments(apps, schema_editor):
    Department = apps.get_model('employee', 'Department')
    departments = [
        'TI', 'Marketing', 'Vendas', 'Logística',
        'Transporte', 'RH', 'Comercial', 'Administrativo'
    ]
    for department in departments:
        Department.objects.create(name=department)

class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_departments)
    ]
