# Generated by Django 5.1.3 on 2024-11-29 19:21

from django.db import migrations

from employee.models import Department, Employee


def create_test_users(apps, schema_editor):
    engineering_department = Department.objects.get(name="Marketing")
    hr_department = Department.objects.get(name="Transporte")

    # Criar empregados com `first_name`
    employee1 = Employee.objects.create(
        username="johndoe",
        first_name="John",  # Adicionando first_name
        last_name="Doe",
        email="johndoe@example.com",
        is_superuser=True,
        is_manager=True,
        department=engineering_department
    )

    employee2 = Employee.objects.create(
        username="janedoe",
        first_name="Jane",  # Adicionando first_name
        last_name="Doe",
        email="janedoe@example.com",
        is_superuser=False,
        is_manager=True,
        department=hr_department
    )

    employee3 = Employee.objects.create(
        username="alice",
        first_name="Alice",  # Adicionando first_name
        last_name="Smith",
        email="alice.smith@example.com",
        is_superuser=False,
        is_manager=False,
        department=engineering_department
    )

class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(create_test_users)
    ]

